<a href="https://colab.research.google.com/github/re7za/Auto-Complete/blob/master/clf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
import numpy as np

x, y = load_diabetes(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=23)

In [4]:
from sklearn.tree import DecisionTreeClassifier

clf_entropy = DecisionTreeClassifier(criterion="entropy", random_state=42, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(x_train,y_train)
 
clf_gini = DecisionTreeClassifier(criterion="gini", random_state=42, max_depth=3, min_samples_leaf=5)
clf_gini.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [9]:
y_gini_p = clf_gini.predict(x_test)
y_entropy_p = clf_entropy.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
print("accuracy_gini:", end=' ')
print(accuracy_score(y_test, y_gini_p))
print(confusion_matrix(y_test, y_gini_p))
print("accuracy_entropy:", end=' ')
print(accuracy_score(y_test,y_entropy_p))
print(confusion_matrix(y_test,y_entropy_p))

accuracy_gini: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
accuracy_entropy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=4)
neighbors.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [12]:
y_neighbors_p = neighbors.predict(x_test)

print("accuracy:", end=' ')
print(accuracy_score(y_test,y_neighbors_p))
print(confusion_matrix(y_test,y_neighbors_p))

accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
from sklearn.naive_bayes import GaussianNB

Gaussian_nb = GaussianNB()
y_predict = Gaussian_nb.fit(x_train, y_train).predict(x_test)
print("Number of mislabeled points out of a total %d points : %d"
      % (x_test.shape[0], (y_test != y_predict).sum()))

print("accuracy:", end=' ')
print(accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))

Number of mislabeled points out of a total 111 points : 111
accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
from sklearn import svm

first_model = svm.SVC(kernel='linear', gamma=1)
first_model.fit(x_train, y_train)
y_svm = first_model.predict(x_test)

print("accuracy:", end=' ')
print(accuracy_score(y_test,y_svm))
print(confusion_matrix(y_test,y_svm))

accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
second_model = svm.SVC(kernel='rbf', gamma=1)

second_model.fit(x_train, y_train)
y_svm2 = second_model.predict(x_test)

print("accuracy:", end=' ')
print(accuracy_score(y_test,y_svm2))
print(confusion_matrix(y_test,y_svm2))

accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
third_model = svm.SVC(kernel='precomputed', gamma=1)

gram_train = np.dot(x_train, x_train.T)
third_model.fit(gram_train, y_train)
# predict on training examples
gram_test = np.dot(x_test, x_train.T)
y_svm3 = third_model.predict(gram_test)

print("accuracy:", end=' ')
print(accuracy_score(y_test,y_svm3))
print(confusion_matrix(y_test,y_svm3))

accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier

my_tree = DecisionTreeClassifier(max_depth=3, random_state=23)
bagging = BaggingClassifier(base_estimator=my_tree, n_estimators=5, max_samples=200, bootstrap=True)
bagging.fit(x_train, y_train)

print(f"Train: {bagging.score(x_train, y_train)}")
print(f"Test: {bagging.score(x_test, y_test)}")

my_tree.fit(x_train, y_train)
print(f"Train: {my_tree.score(x_train, y_train)}")
print(f"Test: {my_tree.score(x_test, y_test)}")

Train score: 0.08157099697885196
Test score: 0.0
Train score: 0.06948640483383686
Test score: 0.0


In [27]:
boost = AdaBoostClassifier(base_estimator=my_tree, n_estimators=5, learning_rate=0.1, random_state=23)
boost.fit(x_train, y_train)

print(f"Train: {boost.score(x_train, y_train)}")
print(f"Test: {boost.score(x_test, y_test)}")

Train: 0.1148036253776435
Test: 0.009009009009009009


In [29]:
from sklearn.neural_network import MLPClassifier
clsfr = MLPClassifier(max_iter=300,random_state=1)
clsfr.fit(x_train, y_train)

y_pp = classifier.predict(x_test)

print("accuracy:", end=' ')
print(accuracy_score(y_test,y_pp))
print(confusion_matrix(y_test,y_pp))

accuracy: 0.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
